name: 'Release UI to production'
run-name: ${{ github.actor }} is deploying
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          cd climbing-grades-web
          npm install shadow-cljs
      - name: Build
        run: |
          cd climbing-grades-web
          npx shadow-cljs release frontend